### ISSUE TITLE
DDSP missing methods for detect_notes and fit_quantile_transform

### ISSUE THREAD

**Issue by VisionaryMind** [mosheman5/timbre_painting#4]
The following import currently fails:

```
from ddsp.colab.colab_utils import (
    auto_tune, detect_notes, fit_quantile_transform, 
    get_tuning_factor, download, play, record, 
    specplot, upload, DEFAULT_SAMPLE_RATE)
```

`detect_notes` and `fit_quantile_transform` methods have apparently been moved to [ddsp.training.postprocessing.py](https://github.com/magenta/ddsp/blob/87fff9a069a727872a9d644e249ae6855b707a49/ddsp/training/postprocessing.py).

**Comment by mosheman5** [comment]
bugfixed, thanks for the solution and bug report! :)
